repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3.11
        # args: ["--line-length=79"]
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        language_version: python3.11.11
#    -   id: poetry-export
    -   id: poetry-install
        language_version: python3.11.11
